# Generated by Django 4.2.5 on 2023-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='town',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
